%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/data/ex01.csv
%
% Auto-generated by MATLAB on 17-May-2022 09:48:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["fecha", "potact_p", "potact_p_v", "potact_n", "potact_n_v", "potreact_1c", "potreact_1c_v", "potreact_2c", "potreact_2c_v", "potreact_3c", "potreact_3c_v", "potreact_4c", "potreact_4c_v", "reserva1", "reserva1_v", "reserva2", "reserva2_v"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "fecha", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "fecha", "EmptyFieldRule", "auto");

% Import the data
ex01 = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/data/ex01.csv", opts);


%% Clear temporary variables
clear opts

%%

dates = contains(ex01.fecha,"+02");
dates = dates(ex01.fecha);
%%
save('data/ex01.mat','ex01')