%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/data/ex01.csv
%
% Auto-generated by MATLAB on 17-May-2022 09:48:26
clear
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["fecha", "potact_p", "potact_p_v", "potact_n", "potact_n_v", "potreact_1c", "potreact_1c_v", "potreact_2c", "potreact_2c_v", "potreact_3c", "potreact_3c_v", "potreact_4c", "potreact_4c_v", "reserva1", "reserva1_v", "reserva2", "reserva2_v"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "fecha", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "fecha", "EmptyFieldRule", "auto");

% Import the data
ex01 = readtable("/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/data/ex01.csv", opts);

ex01(1,:) = [];


%% Clear temporary variables
clear opts

%%
GMT = hours(contains(ex01.fecha,'+01'));

%%

ex01.fecha = char(ex01.fecha);
ex01.fecha = datetime(ex01.fecha(:,1:end-3));
%%
ex01.fecha = ex01.fecha + GMT;
%%
[~,ind] = sort(ex01.fecha);
ex01 = ex01(ind,:);

ex01(ex01.potact_p < 5,:) = [];

%%
save('data/ex01.mat','ex01')
%%
load_curve.DateTime = ex01.fecha;
load_curve.Power    = ex01.potact_p;
load_curve = struct2table(load_curve);
%%
idx =   (load_curve.DateTime > datetime('01-Jan-2013')).* ...
                (load_curve.DateTime <= datetime('31-Dec-2013'))  ;
idx = logical(idx);
load_curve_2013 = load_curve(idx,:);

save('data/ex01_2013.mat','load_curve_2013')
%%
writetable(load_curve_2013,'data/ex01_2013.csv')
