filepathP2 = '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P2/';
mcc -o compute_tarrif_P2 ...
    -W 'main:compute_tarrif_P2,version=1.0' ...
    -T link:exe ...
    -d '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/compiler/compute_tarrif_P2_compiler/for_testing' ...
    -v '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P2/compute_tarrif_P2.m' ...
    -a '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P2/class' ...
    -a '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P2/functions' 
