mcc -o compute_tarrif_P6 ...
    -W 'main:compute_tarrif_P6,version=1.0' ...
    -T link:exe ...
    -d '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/compiler/compute_tarrif_P6/for_testing' ...
    -v '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P6/compute_tarrif_P6.m' ...
    -a '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P6/class' ...
    -a '/Users/djoroya/Dropbox/My Mac (Deyviss’s MacBook Pro)/Documents/GitHub/projects/AGRO-SOFC/Tariff-Optimization/P6/functions' 
