function festivos = holidays_list(year)
% 
% try
% r = webread("https://holidayapi.com/v1/holidays?pretty&key=3b3f26d6-e02e-4515-8e33-6683792226b6&country=ES&year="+year);
% 
% festivos = arrayfun(@(i) datetime(r.holidays(i).date,'Format','yyyy/MM/dd'),1:length(r.holidays))';
% catch
%     festivos = [datetime("01-Jan-"+year) ...
%                 datetime("25-Dec-"+year) ];
% end


     festivos = [datetime("01-Jan-"+year) ...
                 datetime("06-Jan-"+year) ...
                 datetime("01-May-"+year) ...
                 datetime("01-Nov-"+year) ...
                 datetime("12-Oct-"+year)  ...
                 datetime("6-Dec-"+year)  ...
                 datetime("8-Dec-"+year)  ...
                 datetime("25-Dec-"+year) ];
end

